# https://www.elastic.co/blog/getting-started-with-the-elastic-stack-and-docker-compose
---
version: "3.9"
services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.12.2
    environment:
      - DATADIR=/data
      - CONFDIR=/config
      - CONFIG=/config/logstash.conf
      # - PATTERNDIR=/config/patterns
      # - LOGDIR=/logs/
    volumes:
      - ./config:/config
      - ./data/logstash:/data
      - ./example:/logs


  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    environment:
      # these are some default settings to make the setup easier
      # so you do not have to grab the GENERATED ROOT PASSWORD from the MySQL logs
      - MYSQL_ROOT_PASSWORD=mysql_root_password_changeme
      - MYSQL_DATABASE=my-first-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./data/mysql:/var/lib/mysql
      # --mount type=bind,src=/path-on-host-machine/my.cnf,dst=/etc/my.cnf \