# https://www.elastic.co/blog/getting-started-with-the-elastic-stack-and-docker-compose
---
version: "3.9"
services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.12.2
    environment:
      - DATADIR=/data
      - CONFDIR=/config
      - CONFIG=/config/logstash.conf
      # - PATTERNDIR=/config/patterns
      # - LOGDIR=/logs/
    volumes:
      - ./config:/config
      - ./data:/data
      # - ./logs/:/logs/ # the dir with log files for ingest


  # NOTE: non-compose commands;
  # docker run --name=mysql1 -d mysql/mysql-server:8.0
  # docker logs mysql1
  # get the GENERATED ROOT PASSWORD from console output
  # [Entrypoint] GENERATED ROOT PASSWORD: ...
  # NOTE: if you get this error:
  # 2024-04-15T14:52:53.495614Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./ibdata1 error: 11
  # then delete the MySQL data dir and start over...
  # NOTE: docker compose commands
  # docker compose up -d mysql
  # docker compose stop mysql
  # docker inspect mysql
  # NOTE: Check that env vars propagated correctly;
  # $ docker exec mysql env
  # NOTE: enter the contaier and check the db contents
  # NOTE: dont do this, the console does not work correctly; docker exec -ti mysql mysql -u admin -p
  # NOTE: do this; $ docker exec -ti mysql bash
  # bash-4.4# mysql -u admin -p
  # OR do this
  # docker exec -ti mysql mysql -u admin -p -e 'SHOW DATABASES'
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    environment:
      # these are some default settings to make the setup easier
      - MYSQL_ROOT_PASSWORD=mysql_root_password_changeme
      - MYSQL_DATABASE=my-first-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./data/mysql:/var/lib/mysql
      # --mount type=bind,src=/path-on-host-machine/my.cnf,dst=/etc/my.cnf \